import ExcelJS from 'exceljs';
import { isPaymentConfirmed } from '@kiosk/shared';

const pesoFormat = '₱#,##0.00';

function safeText(value) {
  const text = String(value ?? '');
  return /^[=+\-@]/.test(text) ? `'${text}` : text;
}

function amount(centavos) {
  return Number(centavos || 0) / 100;
}

function addHeader(sheet, values) {
  const row = sheet.addRow(values);
  row.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF102440' } };
  row.alignment = { vertical: 'middle' };
  row.height = 22;
}

export function buildSoaSummary(orders, { from, to }) {
  const completedCashOrders = orders.filter(
    (order) =>
      order.status === 'completed' &&
      order.payment_method === 'cash' &&
      isPaymentConfirmed(order.payment_status),
  );
  const completedDemoOrders = orders.filter(
    (order) =>
      order.status === 'completed' &&
      order.payment_method === 'demo_wallet' &&
      isPaymentConfirmed(order.payment_status),
  );
  const pendingCashOrders = orders.filter((order) => order.payment_status === 'pending_cash');
  const sum = (list) => list.reduce((total, order) => total + order.total_centavos, 0);

  return {
    from,
    to,
    orderCount: orders.length,
    completedCashOrderCount: completedCashOrders.length,
    completedDemoOrderCount: completedDemoOrders.length,
    pendingCashOrderCount: pendingCashOrders.length,
    completedCashCentavos: sum(completedCashOrders),
    completedDemoCentavos: sum(completedDemoOrders),
    completedCombinedCentavos: sum(completedCashOrders) + sum(completedDemoOrders),
    pendingCashCentavos: sum(pendingCashOrders),
  };
}

/** Create a workbook with a cash-first, demo-separated statement of account. */
export async function createSoaWorkbook({ summary, orders, items, generatedBy }) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Sweet Gonz Kiosk';
  workbook.created = new Date();
  workbook.properties.title = `Statement of Account ${summary.from} to ${summary.to}`;

  const statement = workbook.addWorksheet('Statement of Account', {
    views: [{ showGridLines: false }],
  });
  statement.mergeCells('A1:D1');
  statement.getCell('A1').value = 'Sweet Gonz — Statement of Account';
  statement.getCell('A1').font = { bold: true, size: 16, color: { argb: 'FF102440' } };
  statement.getCell('A2').value = `Period: ${summary.from} to ${summary.to}`;
  statement.getCell('A3').value = `Generated by: ${safeText(generatedBy)}`;
  statement.getCell('A5').value = 'Real cash only';
  statement.getCell('A5').font = { bold: true, color: { argb: 'FF102440' } };
  statement.addRow(['Completed cash', amount(summary.completedCashCentavos)]);
  statement.addRow(['Pending cash (not received)', amount(summary.pendingCashCentavos)]);
  statement.addRow([
    'Demo wallet (simulated; excluded from cash)',
    amount(summary.completedDemoCentavos),
  ]);
  statement.addRow(['Combined completed (cash + demo)', amount(summary.completedCombinedCentavos)]);
  for (const row of statement.getRows(6, 4)) row.getCell(2).numFmt = pesoFormat;
  statement.getCell('A11').value =
    'Demo wallet entries are simulated pilot data and must not be treated as real cash or e-wallet settlement.';
  statement.mergeCells('A11:D11');
  statement.getCell('A11').alignment = { wrapText: true };
  statement.getCell('A11').font = { italic: true, color: { argb: 'FF704B00' } };
  statement.getColumn(1).width = 48;
  statement.getColumn(2).width = 20;
  statement.getColumn(3).width = 16;
  statement.getColumn(4).width = 16;

  const ordersSheet = workbook.addWorksheet('Orders');
  addHeader(ordersSheet, [
    'Order number',
    'Business date',
    'Placed at (UTC)',
    'Order status',
    'Payment method',
    'Payment status',
    'Total',
  ]);
  for (const order of orders) {
    const row = ordersSheet.addRow([
      safeText(order.order_number),
      safeText(order.business_date),
      safeText(order.created_at),
      safeText(order.status),
      safeText(order.payment_method === 'demo_wallet' ? 'Demo wallet (simulated)' : 'Cash'),
      safeText(order.payment_status),
      amount(order.total_centavos),
    ]);
    row.getCell(7).numFmt = pesoFormat;
  }
  ordersSheet.columns = [
    { width: 24 },
    { width: 15 },
    { width: 25 },
    { width: 16 },
    { width: 28 },
    { width: 20 },
    { width: 15 },
  ];
  ordersSheet.autoFilter = 'A1:G1';
  ordersSheet.views = [{ state: 'frozen', ySplit: 1 }];

  const itemsSheet = workbook.addWorksheet('Order items');
  addHeader(itemsSheet, [
    'Order number',
    'Business date',
    'Order status',
    'Payment method',
    'SKU',
    'Item',
    'Unit price',
    'Quantity',
    'Line total',
  ]);
  for (const item of items) {
    const row = itemsSheet.addRow([
      safeText(item.order_number),
      safeText(item.business_date),
      safeText(item.status),
      safeText(item.payment_method === 'demo_wallet' ? 'Demo wallet (simulated)' : 'Cash'),
      safeText(item.product_sku),
      safeText(item.product_name),
      amount(item.unit_price_centavos),
      item.quantity,
      amount(item.line_total_centavos),
    ]);
    row.getCell(7).numFmt = pesoFormat;
    row.getCell(9).numFmt = pesoFormat;
  }
  itemsSheet.columns = [
    { width: 24 },
    { width: 15 },
    { width: 16 },
    { width: 28 },
    { width: 20 },
    { width: 30 },
    { width: 14 },
    { width: 10 },
    { width: 14 },
  ];
  itemsSheet.autoFilter = 'A1:I1';
  itemsSheet.views = [{ state: 'frozen', ySplit: 1 }];

  return workbook.xlsx.writeBuffer();
}
